### ISSUE TITLE
How to increase the per-env-var limit of envman

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/envman#154]
`envman` by default has a 20KB per-environment (key) value size limit, and a 120KB total envs size limit. If you try to add a value that's larger than 20KB you'll get an error like:

```
$ ruby -e 'puts "a"*40_000' | bitrise envman add --key TEST2
WARN[18:22:12] environment value too large
WARN[18:22:12] environment value size (39.0634765625 KB) - max allowed size: 20 KB
FATA[18:22:12] [ENVMAN] environment value too large - rejected
FATA[18:22:12] Command failed, error: exit status 1
```

This limit is in place because lots of tools, including e.g. `bash` itself, can't work with really large environment variables. If the environment size is too large `bash` for example will fail to run **any** command with an error `argument list too long`.

So, in general, you should find an alternative solution to store larger data, e.g. in files instead of in env vars, but if you can't solve it any other way you can increase these limits via `envman`'s config file (should be stored at `~/.envman/configs.json`).

To increase the per-key value size limit to e.g. 30KB you can use:

```
mkdir -p ~/.envman && echo -e '{"env_bytes_limit_in_kb": 30}' > ~/.envman/configs.json
```

**Comment by aivatradev** [comment]
Hello, I'm getting a size limit of 100kb while exporting an iOS to Itunes Connect through the **Deploy to iTunes Connect** step. I have the **Generate chagelog** step configured before it, but I still get the error:

`+------------------------------------------------------------------------------+

| (9) deploy-to-itunesconnect-application-loader@0.10.1                        |
+------------------------------------------------------------------------------+
| id: deploy-to-itunesconnect-application-loader                               |
| version: 0.10.1                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-03-20T17:05:41Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
WARN[17:05:43] environment list too large                   
WARN[17:05:43] environment list size (100.048828125 KB) - max allowed size: 100 KB 
FATA[17:05:43] [ENVMAN] environment list too large          
ERRO[17:05:43] Step (deploy-to-itunesconnect-application-loader@0.10.1) failed: Failed to export environment list for the Step, error: exit status 1 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | deploy-to-itunesconnect-application-loader@0... (exit code: 1)| 5.37 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ib/steps-deploy-to-itunesconnect-application-loader/issues |
| Source: .../bitrise-steplib/steps-deploy-to-itunesconnect-application-loader |
+---+---------------------------------------------------------------+----------+`

I set up the size limit with 

`mkdir -p ~/.envman && echo -e '{"env_bytes_limit_in_kb": 0}' > ~/.envman/configs.json`

also changed it to be more specific with:

`set -ex
mkdir -p ~/.envman && echo -e '{"env_bytes_limit_in_kb": 300}' > ~/.envman/configs.json`

still get the same 100kb limit error, any idea why?
