### ISSUE TITLE
envman fails when git commit message is too long

### ISSUE THREAD

**Issue by tsonev7** [bitrise-io/envman#171]
When [this](https://github.com/bitrise-steplib/steps-git-clone/blob/a8ba7ff8b83787d4b94b51b6d99ef0673984aa98/main.go#L47) function is executed, an error is thrown if the git commit message is too long.

Is there a restriction for the max length of environment variables ?

**Comment by lpusok** [comment]
Yes there is:
```
defaultEnvBytesLimitInKB     = 20
```

**Comment by tsonev7** [comment]
My concern is that bitrise will fail if the commit message is longer than 20k. Is this restriction correct ?

**Comment by bitce** [comment]
Hi @tsonev7!

Our tooling team is currently discussing how to tackle this problem, we'll make sure to let you know in this thread!

**Comment by happiehappie** [comment]
Any updates how how to deal with this? Are we able to trim the message or sometihng?

**Comment by mjones-droid** [comment]
I just checked in with the devs to see if we have a workaround for this.

**Comment by mjones-droid** [comment]
Information about increasing the size limit of environment variables can be found here:
https://devcenter.bitrise.io/tips-and-tricks/increasing-the-size-limit-of-env-vars/
