### ISSUE TITLE
environment list size (100.048828125 KB) - max allowed size: 100 KB

### ISSUE THREAD

**Issue by aivatradev** [bitrise-io/envman#182]
`+------------------------------------------------------------------------------+

| (9) deploy-to-itunesconnect-application-loader@0.10.1 |
+------------------------------------------------------------------------------+
| id: deploy-to-itunesconnect-application-loader |
| version: 0.10.1 |
| collection: https://github.com/bitrise-io/bitrise-steplib.git |
| toolkit: go |
| time: 2020-03-20T17:05:41Z |
+------------------------------------------------------------------------------+
| |
WARN[17:05:43] environment list too large
WARN[17:05:43] environment list size (100.048828125 KB) - max allowed size: 100 KB
FATA[17:05:43] [ENVMAN] environment list too large
ERRO[17:05:43] Step (deploy-to-itunesconnect-application-loader@0.10.1) failed: Failed to export environment list for the Step, error: exit status 1
| |
+---+---------------------------------------------------------------+----------+
| x | deploy-to-itunesconnect-application-loader@0... (exit code: 1)| 5.37 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ib/steps-deploy-to-itunesconnect-application-loader/issues |
| Source: .../bitrise-steplib/steps-deploy-to-itunesconnect-application-loader |
+---+---------------------------------------------------------------+----------+`

I set up the size limit with

mkdir -p ~/.envman && echo -e '{"env_bytes_limit_in_kb": 0}' > ~/.envman/configs.json

also changed it to be more specific with:

set -ex mkdir -p ~/.envman && echo -e '{"env_bytes_limit_in_kb": 300}' > ~/.envman/configs.json

still get the same 100kb limit error, any idea why?

**Comment by aivatradev** [comment]
FYI, this used to work with one of our branches, then it stopped working, apparently because of the size of the branch history being too large.

**Comment by bitce** [comment]
Hi @aivatradev,

Can you please include an URL for a build where this happens?
